INSERT INTO `travelagencydb`.`activity_category`
(`id`,
`name`,
`description`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{name: }>,
<{description: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`activities`
(`id`,
`destination_id`,
`name`,
`description`,
`activities_category`,
`duration_hours`,
`available_from`,
`available_to`,
`price_local`,
`price_foreigners`,
`min_participate`,
`max_participate`,
`season`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{destination_id: }>,
<{name: }>,
<{description: }>,
<{activities_category: }>,
<{duration_hours: }>,
<{available_from: }>,
<{available_to: }>,
<{price_local: }>,
<{price_foreigners: }>,
<{min_participate: }>,
<{max_participate: }>,
<{season: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`activity_category_images`
(`id`,
`activity_category_id`,
`name`,
`description`,
`image_url`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{activity_category_id: }>,
<{name: }>,
<{description: }>,
<{image_url: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`activities_images`
(`id`,
`activity_id`,
`name`,
`description`,
`image_url`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{activity_id: }>,
<{name: }>,
<{description: }>,
<{image_url: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`activities_requirement`
(`id`,
`activity_id`,
`name`,
`value`,
`description`,
`status`,
`color`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{activity_id: }>,
<{name: }>,
<{value: }>,
<{description: }>,
<{status: }>,
<{color: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`activities_schedule`
(`id`,
`name`,
`activity_id`,
`assume_start_date`,
`assume_end_date`,
`duration_hours_start`,
`duration_hours_end`,
`special_note`,
`description`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{name: }>,
<{activity_id: }>,
<{assume_start_date: }>,
<{assume_end_date: }>,
<{duration_hours_start: }>,
<{duration_hours_end: }>,
<{special_note: }>,
<{description: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`activity_wishlist`
(`id`,
`user_id`,
`activity_id`,
`status_id`,
`created_at`)
VALUES
(<{id: }>,
<{user_id: }>,
<{activity_id: }>,
<{status_id: }>,
<{created_at: CURRENT_TIMESTAMP}>);


INSERT INTO `travelagencydb`.`activities_history`
(`id`,
`activity_schedule_id`,
`name`,
`description`,
`status`,
`number_of_participate`,
`activity_start`,
`activity_end`,
`rating`,
`special_note`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{activity_schedule_id: }>,
<{name: }>,
<{description: }>,
<{status: }>,
<{number_of_participate: }>,
<{activity_start: }>,
<{activity_end: }>,
<{rating: }>,
<{special_note: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`activities_review`
(`id`,
`activity_schedule_id`,
`name`,
`review`,
`rating`,
`description`,
`status`,
`number_of_participate`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{activity_schedule_id: }>,
<{name: }>,
<{review: }>,
<{rating: }>,
<{description: }>,
<{status: }>,
<{number_of_participate: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`activities_history_images`
(`id`,
`activities_history_id`,
`name`,
`description`,
`image_url`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{activities_history_id: }>,
<{name: }>,
<{description: }>,
<{image_url: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`activities_review_images`
(`id`,
`activities_review_id`,
`name`,
`description`,
`image_url`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{activities_review_id: }>,
<{name: }>,
<{description: }>,
<{image_url: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`activity_review_comment`
(`id`,
`activity_review_id`,
`user_id`,
`parent_comment_id`,
`comment`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{activity_review_id: }>,
<{user_id: }>,
<{parent_comment_id: }>,
<{comment: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`activity_review_reaction`
(`id`,
`activity_review_id`,
`user_id`,
`reaction_type_id`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{activity_review_id: }>,
<{user_id: }>,
<{reaction_type_id: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`activity_review_comment_reaction`
(`id`,
`comment_id`,
`user_id`,
`reaction_type_id`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{comment_id: }>,
<{user_id: }>,
<{reaction_type_id: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`activity_wishlist_history`
(`id`,
`user_id`,
`activity_id`,
`wishlist_id`,
`status_id`,
`created_at`)
VALUES
(<{id: }>,
<{user_id: }>,
<{activity_id: }>,
<{wishlist_id: }>,
<{status_id: }>,
<{created_at: CURRENT_TIMESTAMP}>);