CREATE TABLE `activity_category` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `description` text,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `status` (`status`),
  CONSTRAINT `activity_category_ibfk_1` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `activities` (
  `id` int NOT NULL AUTO_INCREMENT,
  `destination_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `activities_category` varchar(100) DEFAULT NULL,
  `duration_hours` decimal(5,2) DEFAULT NULL,
  `available_from` time DEFAULT NULL,
  `available_to` time DEFAULT NULL,
  `price_local` decimal(10,2) DEFAULT NULL,
  `price_foreigners` decimal(10,2) DEFAULT NULL,
  `min_participate` int DEFAULT NULL,
  `max_participate` int DEFAULT NULL,
  `season` varchar(255) DEFAULT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `destination_id` (`destination_id`),
  KEY `status` (`status`),
  CONSTRAINT `activities_ibfk_1` FOREIGN KEY (`destination_id`) REFERENCES `destination` (`destination_id`),
  CONSTRAINT `activities_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `activity_category_images` (
  `id` int NOT NULL AUTO_INCREMENT,
  `activity_category_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `image_url` varchar(500) DEFAULT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `activity_category_id` (`activity_category_id`),
  KEY `status` (`status`),
  CONSTRAINT `activity_category_images_ibfk_1` FOREIGN KEY (`activity_category_id`) REFERENCES `activity_category` (`id`),
  CONSTRAINT `activity_category_images_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `activities_images` (
  `id` int NOT NULL AUTO_INCREMENT,
  `activity_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `image_url` varchar(500) DEFAULT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `activity_id` (`activity_id`),
  KEY `status` (`status`),
  CONSTRAINT `activities_images_ibfk_1` FOREIGN KEY (`activity_id`) REFERENCES `activities` (`id`),
  CONSTRAINT `activities_images_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `activities_requirement` (
  `id` int NOT NULL AUTO_INCREMENT,
  `activity_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `value` varchar(255) DEFAULT NULL,
  `description` text,
  `status` int NOT NULL,
  `color` varchar(50) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `activity_id` (`activity_id`),
  KEY `status` (`status`),
  CONSTRAINT `activities_requirement_ibfk_1` FOREIGN KEY (`activity_id`) REFERENCES `activities` (`id`),
  CONSTRAINT `activities_requirement_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `activities_schedule` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `activity_id` int NOT NULL,
  `assume_start_date` date DEFAULT NULL,
  `assume_end_date` date DEFAULT NULL,
  `duration_hours_start` decimal(5,2) DEFAULT NULL,
  `duration_hours_end` decimal(5,2) DEFAULT NULL,
  `special_note` text,
  `description` text,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `activity_id` (`activity_id`),
  KEY `status` (`status`),
  CONSTRAINT `activities_schedule_ibfk_1` FOREIGN KEY (`activity_id`) REFERENCES `activities` (`id`),
  CONSTRAINT `activities_schedule_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `activity_wishlist` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `activity_id` int NOT NULL,
  `status_id` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `activity_id` (`activity_id`),
  KEY `status_id` (`status_id`),
  CONSTRAINT `activity_wishlist_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `activity_wishlist_ibfk_2` FOREIGN KEY (`activity_id`) REFERENCES `activities` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `activity_wishlist_ibfk_3` FOREIGN KEY (`status_id`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `activities_history` (
  `id` int NOT NULL AUTO_INCREMENT,
  `activity_schedule_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `status` int NOT NULL,
  `number_of_participate` int DEFAULT NULL,
  `activity_start` datetime DEFAULT NULL,
  `activity_end` datetime DEFAULT NULL,
  `rating` decimal(3,2) DEFAULT NULL,
  `special_note` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `activity_schedule_id` (`activity_schedule_id`),
  KEY `status` (`status`),
  CONSTRAINT `activities_history_ibfk_1` FOREIGN KEY (`activity_schedule_id`) REFERENCES `activities_schedule` (`id`),
  CONSTRAINT `activities_history_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `activities_review` (
  `id` int NOT NULL AUTO_INCREMENT,
  `activity_schedule_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `review` text,
  `rating` decimal(3,2) DEFAULT NULL,
  `description` text,
  `status` int NOT NULL,
  `number_of_participate` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `activity_schedule_id` (`activity_schedule_id`),
  KEY `status` (`status`),
  CONSTRAINT `activities_review_ibfk_1` FOREIGN KEY (`activity_schedule_id`) REFERENCES `activities_schedule` (`id`),
  CONSTRAINT `activities_review_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `activities_history_images` (
  `id` int NOT NULL AUTO_INCREMENT,
  `activities_history_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `image_url` varchar(500) DEFAULT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `activities_history_id` (`activities_history_id`),
  KEY `status` (`status`),
  CONSTRAINT `activities_history_images_ibfk_1` FOREIGN KEY (`activities_history_id`) REFERENCES `activities_history` (`id`),
  CONSTRAINT `activities_history_images_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `activities_review_images` (
  `id` int NOT NULL AUTO_INCREMENT,
  `activities_review_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `image_url` varchar(500) DEFAULT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `activities_review_id` (`activities_review_id`),
  KEY `status` (`status`),
  CONSTRAINT `activities_review_images_ibfk_1` FOREIGN KEY (`activities_review_id`) REFERENCES `activities_review` (`id`),
  CONSTRAINT `activities_review_images_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `activity_review_comment` (
  `id` int NOT NULL AUTO_INCREMENT,
  `activity_review_id` int NOT NULL,
  `user_id` int NOT NULL,
  `parent_comment_id` int DEFAULT NULL,
  `comment` text NOT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `activity_review_id` (`activity_review_id`),
  KEY `user_id` (`user_id`),
  KEY `parent_comment_id` (`parent_comment_id`),
  KEY `status` (`status`),
  CONSTRAINT `activity_review_comment_ibfk_1` FOREIGN KEY (`activity_review_id`) REFERENCES `activities_review` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `activity_review_comment_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `activity_review_comment_ibfk_3` FOREIGN KEY (`parent_comment_id`) REFERENCES `activity_review_comment` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `activity_review_comment_ibfk_4` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `activity_review_reaction` (
  `id` int NOT NULL AUTO_INCREMENT,
  `activity_review_id` int NOT NULL,
  `user_id` int NOT NULL,
  `reaction_type_id` int NOT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_review_user_reaction` (`activity_review_id`,`user_id`),
  KEY `user_id` (`user_id`),
  KEY `reaction_type_id` (`reaction_type_id`),
  KEY `status` (`status`),
  CONSTRAINT `activity_review_reaction_ibfk_1` FOREIGN KEY (`activity_review_id`) REFERENCES `activities_review` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `activity_review_reaction_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `activity_review_reaction_ibfk_3` FOREIGN KEY (`reaction_type_id`) REFERENCES `reaction_type` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `activity_review_reaction_ibfk_4` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `activity_review_comment_reaction` (
  `id` int NOT NULL AUTO_INCREMENT,
  `comment_id` int NOT NULL,
  `user_id` int NOT NULL,
  `reaction_type_id` int NOT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_comment_user_reaction` (`comment_id`,`user_id`),
  KEY `user_id` (`user_id`),
  KEY `reaction_type_id` (`reaction_type_id`),
  KEY `status` (`status`),
  CONSTRAINT `activity_review_comment_reaction_ibfk_1` FOREIGN KEY (`comment_id`) REFERENCES `activity_review_comment` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `activity_review_comment_reaction_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `activity_review_comment_reaction_ibfk_3` FOREIGN KEY (`reaction_type_id`) REFERENCES `reaction_type` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `activity_review_comment_reaction_ibfk_4` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `activity_wishlist_history` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `activity_id` int NOT NULL,
  `wishlist_id` int NOT NULL,
  `status_id` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `activity_id` (`activity_id`),
  KEY `wishlist_id` (`wishlist_id`),
  KEY `status_id` (`status_id`),
  CONSTRAINT `activity_wishlist_history_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `activity_wishlist_history_ibfk_2` FOREIGN KEY (`activity_id`) REFERENCES `activities` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `activity_wishlist_history_ibfk_3` FOREIGN KEY (`wishlist_id`) REFERENCES `activity_wishlist` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `activity_wishlist_history_ibfk_4` FOREIGN KEY (`status_id`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);