CREATE TABLE `destination_categories` (
  `id` int NOT NULL AUTO_INCREMENT,
  `category` varchar(100) NOT NULL,
  `description` text,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `status` (`status`),
  CONSTRAINT `destination_categories_ibfk_1` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `destination` (
  `destination_id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` text,
  `status` int NOT NULL,
  `destination_category` int DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `latitude` decimal(10,8) DEFAULT NULL,
  `longitude` decimal(11,8) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  `extra_price` int DEFAULT '0',
  `extra_price_note` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`destination_id`),
  KEY `destination_category` (`destination_category`),
  KEY `status` (`status`),
  CONSTRAINT `destination_ibfk_1` FOREIGN KEY (`destination_category`) REFERENCES `destination_categories` (`id`),
  CONSTRAINT `destination_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `destination_categories_images` (
  `id` int NOT NULL AUTO_INCREMENT,
  `destination_categories_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `image_url` varchar(500) DEFAULT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `destination_categories_id` (`destination_categories_id`),
  KEY `status` (`status`),
  CONSTRAINT `destination_categories_images_ibfk_1` FOREIGN KEY (`destination_categories_id`) REFERENCES `destination_categories` (`id`),
  CONSTRAINT `destination_categories_images_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `destination_images` (
  `id` int NOT NULL AUTO_INCREMENT,
  `destination_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `image_url` varchar(500) DEFAULT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `destination_id` (`destination_id`),
  KEY `status` (`status`),
  CONSTRAINT `destination_images_ibfk_1` FOREIGN KEY (`destination_id`) REFERENCES `destination` (`destination_id`),
  CONSTRAINT `destination_images_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `destination_history` (
  `id` int NOT NULL AUTO_INCREMENT,
  `destination_id` int NOT NULL,
  `package_schedule_id` int DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `description` text,
  `event_date` date DEFAULT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `destination_id` (`destination_id`),
  KEY `package_schedule_id` (`package_schedule_id`),
  KEY `status` (`status`),
  CONSTRAINT `destination_history_ibfk_1` FOREIGN KEY (`destination_id`) REFERENCES `destination` (`destination_id`),
  CONSTRAINT `destination_history_ibfk_2` FOREIGN KEY (`package_schedule_id`) REFERENCES `package_schedule` (`id`),
  CONSTRAINT `destination_history_ibfk_3` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `destination_history_images` (
  `id` int NOT NULL AUTO_INCREMENT,
  `destination_history_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `image_url` varchar(500) DEFAULT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `destination_history_id` (`destination_history_id`),
  KEY `status` (`status`),
  CONSTRAINT `destination_history_images_ibfk_1` FOREIGN KEY (`destination_history_id`) REFERENCES `destination_history` (`id`),
  CONSTRAINT `destination_history_images_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `destination_review` (
  `review_id` int NOT NULL AUTO_INCREMENT,
  `destination_id` int NOT NULL,
  `user_id` int NOT NULL,
  `review_text` text,
  `rating` decimal(3,2) DEFAULT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`review_id`),
  KEY `destination_id` (`destination_id`),
  KEY `user_id` (`user_id`),
  KEY `status` (`status`),
  CONSTRAINT `destination_review_ibfk_1` FOREIGN KEY (`destination_id`) REFERENCES `destination` (`destination_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `destination_review_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `destination_review_ibfk_3` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `destination_review_images` (
  `image_id` int NOT NULL AUTO_INCREMENT,
  `review_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `image_url` varchar(255) NOT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`image_id`),
  KEY `review_id` (`review_id`),
  KEY `status` (`status`),
  CONSTRAINT `destination_review_images_ibfk_1` FOREIGN KEY (`review_id`) REFERENCES `destination_review` (`review_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `destination_review_images_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `destination_review_comment` (
  `comment_id` int NOT NULL AUTO_INCREMENT,
  `review_id` int NOT NULL,
  `user_id` int NOT NULL,
  `comment_text` text NOT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  `parent_comment_id` int DEFAULT NULL,
  PRIMARY KEY (`comment_id`),
  KEY `review_id` (`review_id`),
  KEY `user_id` (`user_id`),
  KEY `status` (`status`),
  KEY `parent_comment_id` (`parent_comment_id`),
  CONSTRAINT `destination_review_comment_ibfk_1` FOREIGN KEY (`review_id`) REFERENCES `destination_review` (`review_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `destination_review_comment_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `destination_review_comment_ibfk_3` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `destination_review_comment_ibfk_4` FOREIGN KEY (`parent_comment_id`) REFERENCES `destination_review_comment` (`comment_id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE `destination_review_reaction` (
  `review_reaction_id` int NOT NULL AUTO_INCREMENT,
  `review_id` int NOT NULL,
  `user_id` int NOT NULL,
  `reaction_type_id` int NOT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`review_reaction_id`),
  KEY `review_id` (`review_id`),
  KEY `user_id` (`user_id`),
  KEY `reaction_type_id` (`reaction_type_id`),
  KEY `status` (`status`),
  CONSTRAINT `destination_review_reaction_ibfk_1` FOREIGN KEY (`review_id`) REFERENCES `destination_review` (`review_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `destination_review_reaction_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `destination_review_reaction_ibfk_3` FOREIGN KEY (`reaction_type_id`) REFERENCES `reaction_type` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `destination_review_reaction_ibfk_4` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `destination_review_comment_reaction` (
  `comment_reaction_id` int NOT NULL AUTO_INCREMENT,
  `comment_id` int NOT NULL,
  `user_id` int NOT NULL,
  `reaction_type_id` int NOT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`comment_reaction_id`),
  KEY `comment_id` (`comment_id`),
  KEY `user_id` (`user_id`),
  KEY `reaction_type_id` (`reaction_type_id`),
  KEY `status` (`status`),
  CONSTRAINT `destination_review_comment_reaction_ibfk_1` FOREIGN KEY (`comment_id`) REFERENCES `destination_review_comment` (`comment_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `destination_review_comment_reaction_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `destination_review_comment_reaction_ibfk_3` FOREIGN KEY (`reaction_type_id`) REFERENCES `reaction_type` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `destination_review_comment_reaction_ibfk_4` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `destination_wishlist` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `destination_id` int NOT NULL,
  `status_id` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `destination_id` (`destination_id`),
  KEY `status_id` (`status_id`),
  CONSTRAINT `destination_wishlist_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `destination_wishlist_ibfk_2` FOREIGN KEY (`destination_id`) REFERENCES `destination` (`destination_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `destination_wishlist_ibfk_3` FOREIGN KEY (`status_id`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `destination_wishlist_history` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `destination_id` int NOT NULL,
  `wishlist_id` int NOT NULL,
  `status_id` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `destination_id` (`destination_id`),
  KEY `wishlist_id` (`wishlist_id`),
  KEY `status_id` (`status_id`),
  CONSTRAINT `destination_wishlist_history_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `destination_wishlist_history_ibfk_2` FOREIGN KEY (`destination_id`) REFERENCES `destination` (`destination_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `destination_wishlist_history_ibfk_3` FOREIGN KEY (`wishlist_id`) REFERENCES `destination_wishlist` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `destination_wishlist_history_ibfk_4` FOREIGN KEY (`status_id`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);