INSERT INTO `travelagencydb`.`nav_bar_status`
(`id`,
`name`,
`description`,
`common_status_id`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{name: }>,
<{description: }>,
<{common_status_id: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`nav_bar`
(`id`,
`name`,
`description`,
`status_id`,
`link_url`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{name: }>,
<{description: }>,
<{status_id: }>,
<{link_url: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`nav_bar_submenu`
(`id`,
`nav_bar_id`,
`parent_submenu_id`,
`name`,
`description`,
`link_url`,
`icon_class`,
`sort_order`,
`opens_in_new_tab`,
`is_featured`,
`status_id`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{nav_bar_id: }>,
<{parent_submenu_id: }>,
<{name: }>,
<{description: }>,
<{link_url: }>,
<{icon_class: }>,
<{sort_order: 0}>,
<{opens_in_new_tab: 0}>,
<{is_featured: 0}>,
<{status_id: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);