CREATE TABLE `package_type` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `description` text,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `status` (`status`),
  CONSTRAINT `package_type_ibfk_1` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `packages` (
  `package_id` int NOT NULL AUTO_INCREMENT,
  `package_type_id` int DEFAULT NULL,
  `tour_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `total_price` decimal(10,2) DEFAULT NULL,
  `discount_percentage` decimal(5,2) DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `color` varchar(50) DEFAULT NULL,
  `status` int NOT NULL,
  `hover_color` varchar(50) DEFAULT NULL,
  `min_person_count` int DEFAULT NULL,
  `max_person_count` int DEFAULT NULL,
  `price_per_person` decimal(10,2) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`package_id`),
  KEY `tour_id` (`tour_id`),
  KEY `status` (`status`),
  KEY `fk_package_type` (`package_type_id`),
  CONSTRAINT `fk_package_type` FOREIGN KEY (`package_type_id`) REFERENCES `package_type` (`id`),
  CONSTRAINT `packages_ibfk_1` FOREIGN KEY (`tour_id`) REFERENCES `tour` (`tour_id`),
  CONSTRAINT `packages_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `package_condition` (
  `package_condition_id` int NOT NULL AUTO_INCREMENT,
  `package_id` int NOT NULL,
  `condition_text` text NOT NULL,
  `display_order` int DEFAULT '0',
  `status_id` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`package_condition_id`),
  KEY `fk_package_condition_tour` (`package_id`),
  KEY `fk_package_condition_status` (`status_id`),
  KEY `fk_package_condition_terminated_by` (`terminated_by`),
  CONSTRAINT `fk_package_condition_status` FOREIGN KEY (`status_id`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_package_condition_terminated_by` FOREIGN KEY (`terminated_by`) REFERENCES `user` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_package_condition_tour` FOREIGN KEY (`package_id`) REFERENCES `packages` (`package_id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `package_day_accommodation` (
  `package_day_accommodation_id` int NOT NULL AUTO_INCREMENT,
  `package_id` int NOT NULL,
  `day_number` int NOT NULL,
  `breakfast` tinyint(1) DEFAULT '0',
  `breakfast_description` text,
  `lunch` tinyint(1) DEFAULT '0',
  `lunch_description` text,
  `dinner` tinyint(1) DEFAULT '0',
  `dinner_description` text,
  `morning_tea` tinyint(1) DEFAULT '0',
  `morning_tea_description` text,
  `evening_tea` tinyint(1) DEFAULT '0',
  `evening_tea_description` text,
  `snacks` tinyint(1) DEFAULT '0',
  `snack_note` text,
  `hotel_id` int DEFAULT NULL,
  `transport_id` int DEFAULT NULL,
  `other_notes` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `status` int NOT NULL DEFAULT '1',
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  `local_price` int DEFAULT NULL,
  `price` int DEFAULT NULL,
  `discount` int DEFAULT NULL,
  `service_charge` int DEFAULT NULL,
  `tax` int DEFAULT NULL,
  `extra_charge` int DEFAULT NULL,
  `extra_charge_note` varchar(1000) DEFAULT NULL,
  `transport_cost` int DEFAULT '0',
  PRIMARY KEY (`package_day_accommodation_id`),
  UNIQUE KEY `uq_package_day` (`package_id`,`day_number`),
  KEY `fk_pda_hotel` (`hotel_id`),
  KEY `fk_pda_transport` (`transport_id`),
  KEY `idx_pda_status` (`status`),
  KEY `idx_pda_terminated_at` (`terminated_at`),
  KEY `idx_pda_terminated_by` (`terminated_by`),
  CONSTRAINT `fk_pda_hotel` FOREIGN KEY (`hotel_id`) REFERENCES `service_provider` (`service_provider_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_pda_package` FOREIGN KEY (`package_id`) REFERENCES `packages` (`package_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_pda_status` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_pda_terminated_by` FOREIGN KEY (`terminated_by`) REFERENCES `user` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_pda_transport` FOREIGN KEY (`transport_id`) REFERENCES `vehicles` (`vehicle_id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE `package_exclusion` (
  `package_exclusion_id` int NOT NULL AUTO_INCREMENT,
  `package_id` int NOT NULL,
  `exclusion_text` text NOT NULL,
  `display_order` int DEFAULT '0',
  `status_id` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`package_exclusion_id`),
  KEY `fk_package_exclusion_tour` (`package_id`),
  KEY `fk_package_exclusion_status` (`status_id`),
  KEY `fk_package_exclusion_terminated_by` (`terminated_by`),
  CONSTRAINT `fk_package_exclusion_status` FOREIGN KEY (`status_id`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_package_exclusion_terminated_by` FOREIGN KEY (`terminated_by`) REFERENCES `user` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_package_exclusion_tour` FOREIGN KEY (`package_id`) REFERENCES `packages` (`package_id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `package_images` (
  `id` int NOT NULL AUTO_INCREMENT,
  `package_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `status` int NOT NULL,
  `image_url` varchar(500) DEFAULT NULL,
  `color` varchar(50) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `package_id` (`package_id`),
  KEY `status` (`status`),
  CONSTRAINT `package_images_ibfk_1` FOREIGN KEY (`package_id`) REFERENCES `packages` (`package_id`),
  CONSTRAINT `package_images_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `package_inclusion` (
  `package_inclusion_id` int NOT NULL AUTO_INCREMENT,
  `package_id` int NOT NULL,
  `inclusion_text` text NOT NULL,
  `display_order` int DEFAULT '0',
  `status_id` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`package_inclusion_id`),
  KEY `fk_package_inclusion_tour` (`package_id`),
  KEY `fk_package_inclusion_status` (`status_id`),
  KEY `fk_package_inclusion_terminated_by` (`terminated_by`),
  CONSTRAINT `fk_package_inclusion_status` FOREIGN KEY (`status_id`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_package_inclusion_terminated_by` FOREIGN KEY (`terminated_by`) REFERENCES `user` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_package_inclusion_tour` FOREIGN KEY (`package_id`) REFERENCES `packages` (`package_id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `package_schedule` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `package_id` int NOT NULL,
  `assume_start_date` date DEFAULT NULL,
  `assume_end_date` date DEFAULT NULL,
  `duration_start` int DEFAULT NULL,
  `duration_end` int DEFAULT NULL,
  `special_note` text,
  `description` text,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  `tour_shedule_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `package_id` (`package_id`),
  KEY `status` (`status`),
  CONSTRAINT `package_schedule_ibfk_1` FOREIGN KEY (`package_id`) REFERENCES `packages` (`package_id`),
  CONSTRAINT `package_schedule_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `package_travel_tips` (
  `package_travel_tip_id` int NOT NULL AUTO_INCREMENT,
  `package_id` int NOT NULL,
  `tip_title` varchar(150) DEFAULT NULL,
  `tip_description` text NOT NULL,
  `display_order` int DEFAULT '1',
  `status_id` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`package_travel_tip_id`),
  KEY `package_id` (`package_id`),
  KEY `status_id` (`status_id`),
  CONSTRAINT `package_travel_tips_ibfk_1` FOREIGN KEY (`package_id`) REFERENCES `packages` (`package_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `package_travel_tips_ibfk_2` FOREIGN KEY (`status_id`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `package_wishlist` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `package_id` int NOT NULL,
  `status_id` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `package_id` (`package_id`),
  KEY `status_id` (`status_id`),
  CONSTRAINT `package_wishlist_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `package_wishlist_ibfk_2` FOREIGN KEY (`package_id`) REFERENCES `packages` (`package_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `package_wishlist_ibfk_3` FOREIGN KEY (`status_id`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `package_history` (
  `id` int NOT NULL AUTO_INCREMENT,
  `package_schedule_id` int NOT NULL,
  `number_of_participate` int DEFAULT NULL,
  `rating` decimal(3,2) DEFAULT NULL,
  `duration` int DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `status` int NOT NULL,
  `color` varchar(50) DEFAULT NULL,
  `hover_color` varchar(50) DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `package_schedule_id` (`package_schedule_id`),
  KEY `status` (`status`),
  CONSTRAINT `package_history_ibfk_1` FOREIGN KEY (`package_schedule_id`) REFERENCES `package_schedule` (`id`),
  CONSTRAINT `package_history_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `package_history_images` (
  `id` int NOT NULL AUTO_INCREMENT,
  `package_schedule_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `image_url` varchar(500) DEFAULT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `package_schedule_id` (`package_schedule_id`),
  KEY `status` (`status`),
  CONSTRAINT `package_history_images_ibfk_1` FOREIGN KEY (`package_schedule_id`) REFERENCES `package_schedule` (`id`),
  CONSTRAINT `package_history_images_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `package_review` (
  `id` int NOT NULL AUTO_INCREMENT,
  `package_schedule_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `review` text,
  `rating` decimal(3,2) DEFAULT NULL,
  `description` text,
  `status` int NOT NULL,
  `number_of_participate` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `package_schedule_id` (`package_schedule_id`),
  KEY `status` (`status`),
  CONSTRAINT `package_review_ibfk_1` FOREIGN KEY (`package_schedule_id`) REFERENCES `package_schedule` (`id`),
  CONSTRAINT `package_review_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `package_review_images` (
  `id` int NOT NULL AUTO_INCREMENT,
  `package_review_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `image_url` varchar(500) DEFAULT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `package_review_id` (`package_review_id`),
  KEY `status` (`status`),
  CONSTRAINT `package_review_images_ibfk_1` FOREIGN KEY (`package_review_id`) REFERENCES `package_review` (`id`),
  CONSTRAINT `package_review_images_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `package_review_comment` (
  `id` int NOT NULL AUTO_INCREMENT,
  `package_review_id` int NOT NULL,
  `user_id` int NOT NULL,
  `parent_comment_id` int DEFAULT NULL,
  `comment` text NOT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `package_review_id` (`package_review_id`),
  KEY `user_id` (`user_id`),
  KEY `parent_comment_id` (`parent_comment_id`),
  KEY `status` (`status`),
  CONSTRAINT `package_review_comment_ibfk_1` FOREIGN KEY (`package_review_id`) REFERENCES `package_review` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `package_review_comment_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `package_review_comment_ibfk_3` FOREIGN KEY (`parent_comment_id`) REFERENCES `package_review_comment` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `package_review_comment_ibfk_4` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `package_review_reaction` (
  `id` int NOT NULL AUTO_INCREMENT,
  `package_review_id` int NOT NULL,
  `user_id` int NOT NULL,
  `reaction_type_id` int NOT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `package_review_id` (`package_review_id`,`user_id`,`reaction_type_id`),
  KEY `user_id` (`user_id`),
  KEY `reaction_type_id` (`reaction_type_id`),
  KEY `status` (`status`),
  CONSTRAINT `package_review_reaction_ibfk_1` FOREIGN KEY (`package_review_id`) REFERENCES `package_review` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `package_review_reaction_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `package_review_reaction_ibfk_3` FOREIGN KEY (`reaction_type_id`) REFERENCES `reaction_type` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `package_review_reaction_ibfk_4` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `package_review_comment_reaction` (
  `id` int NOT NULL AUTO_INCREMENT,
  `comment_id` int NOT NULL,
  `user_id` int NOT NULL,
  `reaction_type_id` int NOT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `comment_id` (`comment_id`,`user_id`,`reaction_type_id`),
  KEY `user_id` (`user_id`),
  KEY `reaction_type_id` (`reaction_type_id`),
  KEY `status` (`status`),
  CONSTRAINT `package_review_comment_reaction_ibfk_1` FOREIGN KEY (`comment_id`) REFERENCES `package_review_comment` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `package_review_comment_reaction_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `package_review_comment_reaction_ibfk_3` FOREIGN KEY (`reaction_type_id`) REFERENCES `reaction_type` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `package_review_comment_reaction_ibfk_4` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `package_wishlist_history` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `package_id` int NOT NULL,
  `wishlist_id` int NOT NULL,
  `status_id` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `package_id` (`package_id`),
  KEY `wishlist_id` (`wishlist_id`),
  KEY `status_id` (`status_id`),
  CONSTRAINT `package_wishlist_history_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `package_wishlist_history_ibfk_2` FOREIGN KEY (`package_id`) REFERENCES `packages` (`package_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `package_wishlist_history_ibfk_3` FOREIGN KEY (`wishlist_id`) REFERENCES `package_wishlist` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `package_wishlist_history_ibfk_4` FOREIGN KEY (`status_id`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);