INSERT INTO `travelagencydb`.`package_type`
(`id`,
`name`,
`description`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{name: }>,
<{description: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`packages`
(`package_id`,
`package_type_id`,
`tour_id`,
`name`,
`description`,
`total_price`,
`discount_percentage`,
`start_date`,
`end_date`,
`color`,
`status`,
`hover_color`,
`min_person_count`,
`max_person_count`,
`price_per_person`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{package_id: }>,
<{package_type_id: }>,
<{tour_id: }>,
<{name: }>,
<{description: }>,
<{total_price: }>,
<{discount_percentage: }>,
<{start_date: }>,
<{end_date: }>,
<{color: }>,
<{status: }>,
<{hover_color: }>,
<{min_person_count: }>,
<{max_person_count: }>,
<{price_per_person: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`package_condition`
(`package_condition_id`,
`package_id`,
`condition_text`,
`display_order`,
`status_id`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{package_condition_id: }>,
<{package_id: }>,
<{condition_text: }>,
<{display_order: 0}>,
<{status_id: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`package_day_accommodation`
(`package_day_accommodation_id`,
`package_id`,
`day_number`,
`breakfast`,
`breakfast_description`,
`lunch`,
`lunch_description`,
`dinner`,
`dinner_description`,
`morning_tea`,
`morning_tea_description`,
`evening_tea`,
`evening_tea_description`,
`snacks`,
`snack_note`,
`hotel_id`,
`transport_id`,
`other_notes`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`status`,
`terminated_at`,
`terminated_by`,
`local_price`,
`price`,
`discount`,
`service_charge`,
`tax`,
`extra_charge`,
`extra_charge_note`,
`transport_cost`)
VALUES
(<{package_day_accommodation_id: }>,
<{package_id: }>,
<{day_number: }>,
<{breakfast: 0}>,
<{breakfast_description: }>,
<{lunch: 0}>,
<{lunch_description: }>,
<{dinner: 0}>,
<{dinner_description: }>,
<{morning_tea: 0}>,
<{morning_tea_description: }>,
<{evening_tea: 0}>,
<{evening_tea_description: }>,
<{snacks: 0}>,
<{snack_note: }>,
<{hotel_id: }>,
<{transport_id: }>,
<{other_notes: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{status: 1}>,
<{terminated_at: }>,
<{terminated_by: }>,
<{local_price: }>,
<{price: }>,
<{discount: }>,
<{service_charge: }>,
<{tax: }>,
<{extra_charge: }>,
<{extra_charge_note: }>,
<{transport_cost: 0}>);

INSERT INTO `travelagencydb`.`package_exclusion`
(`package_exclusion_id`,
`package_id`,
`exclusion_text`,
`display_order`,
`status_id`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{package_exclusion_id: }>,
<{package_id: }>,
<{exclusion_text: }>,
<{display_order: 0}>,
<{status_id: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`package_images`
(`id`,
`package_id`,
`name`,
`description`,
`status`,
`image_url`,
`color`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{package_id: }>,
<{name: }>,
<{description: }>,
<{status: }>,
<{image_url: }>,
<{color: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`package_inclusion`
(`package_inclusion_id`,
`package_id`,
`inclusion_text`,
`display_order`,
`status_id`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{package_inclusion_id: }>,
<{package_id: }>,
<{inclusion_text: }>,
<{display_order: 0}>,
<{status_id: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`package_schedule`
(`id`,
`name`,
`package_id`,
`assume_start_date`,
`assume_end_date`,
`duration_start`,
`duration_end`,
`special_note`,
`description`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`,
`tour_shedule_id`)
VALUES
(<{id: }>,
<{name: }>,
<{package_id: }>,
<{assume_start_date: }>,
<{assume_end_date: }>,
<{duration_start: }>,
<{duration_end: }>,
<{special_note: }>,
<{description: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>,
<{tour_shedule_id: }>);

INSERT INTO `travelagencydb`.`package_travel_tips`
(`package_travel_tip_id`,
`package_id`,
`tip_title`,
`tip_description`,
`display_order`,
`status_id`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{package_travel_tip_id: }>,
<{package_id: }>,
<{tip_title: }>,
<{tip_description: }>,
<{display_order: 1}>,
<{status_id: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);


INSERT INTO `travelagencydb`.`package_wishlist`
(`id`,
`user_id`,
`package_id`,
`status_id`,
`created_at`)
VALUES
(<{id: }>,
<{user_id: }>,
<{package_id: }>,
<{status_id: }>,
<{created_at: CURRENT_TIMESTAMP}>);

INSERT INTO `travelagencydb`.`package_history`
(`id`,
`package_schedule_id`,
`number_of_participate`,
`rating`,
`duration`,
`name`,
`description`,
`status`,
`color`,
`hover_color`,
`start_date`,
`end_date`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{package_schedule_id: }>,
<{number_of_participate: }>,
<{rating: }>,
<{duration: }>,
<{name: }>,
<{description: }>,
<{status: }>,
<{color: }>,
<{hover_color: }>,
<{start_date: }>,
<{end_date: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`package_history_images`
(`id`,
`package_schedule_id`,
`name`,
`description`,
`image_url`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{package_schedule_id: }>,
<{name: }>,
<{description: }>,
<{image_url: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`package_review`
(`id`,
`package_schedule_id`,
`name`,
`review`,
`rating`,
`description`,
`status`,
`number_of_participate`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{package_schedule_id: }>,
<{name: }>,
<{review: }>,
<{rating: }>,
<{description: }>,
<{status: }>,
<{number_of_participate: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`package_review_images`
(`id`,
`package_review_id`,
`name`,
`description`,
`image_url`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{package_review_id: }>,
<{name: }>,
<{description: }>,
<{image_url: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`package_review_comment`
(`id`,
`package_review_id`,
`user_id`,
`parent_comment_id`,
`comment`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{package_review_id: }>,
<{user_id: }>,
<{parent_comment_id: }>,
<{comment: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`package_review_reaction`
(`id`,
`package_review_id`,
`user_id`,
`reaction_type_id`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{package_review_id: }>,
<{user_id: }>,
<{reaction_type_id: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`package_review_comment_reaction`
(`id`,
`comment_id`,
`user_id`,
`reaction_type_id`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{comment_id: }>,
<{user_id: }>,
<{reaction_type_id: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`package_wishlist_history`
(`id`,
`user_id`,
`package_id`,
`wishlist_id`,
`status_id`,
`created_at`)
VALUES
(<{id: }>,
<{user_id: }>,
<{package_id: }>,
<{wishlist_id: }>,
<{status_id: }>,
<{created_at: CURRENT_TIMESTAMP}>);