CREATE TABLE `tour_category` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `description` text,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `status` (`status`),
  CONSTRAINT `tour_category_ibfk_1` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `tour_type` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `description` text,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `status` (`status`),
  CONSTRAINT `tour_type_ibfk_1` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `tour_hero_section` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `image_url` varchar(255) NOT NULL,
  `title` varchar(100) DEFAULT NULL,
  `subtitle` varchar(150) DEFAULT NULL,
  `description` text,
  `primary_button_text` varchar(50) DEFAULT NULL,
  `primary_button_link` varchar(255) DEFAULT NULL,
  `secondary_button_text` varchar(50) DEFAULT NULL,
  `secondary_button_link` varchar(255) DEFAULT NULL,
  `status` int NOT NULL,
  `order` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `status` (`status`),
  CONSTRAINT `tour_hero_section_ibfk_1` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `tour` (
  `tour_id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` text,
  `tour_type` int DEFAULT NULL,
  `tour_category` int DEFAULT NULL,
  `duration` int DEFAULT NULL,
  `latitude` decimal(10,8) DEFAULT NULL,
  `longitude` decimal(11,8) DEFAULT NULL,
  `start_location` varchar(255) DEFAULT NULL,
  `end_location` varchar(255) DEFAULT NULL,
  `season` int DEFAULT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  `assign_to` int DEFAULT NULL,
  `assign_message` varchar(1000) DEFAULT 'This tour is managed by a dedicated coordinator who will assist with planning, bookings, and support for a smooth travel experience.',
  PRIMARY KEY (`tour_id`),
  KEY `tour_type` (`tour_type`),
  KEY `tour_category` (`tour_category`),
  KEY `season` (`season`),
  KEY `status` (`status`),
  CONSTRAINT `tour_ibfk_1` FOREIGN KEY (`tour_type`) REFERENCES `tour_type` (`id`),
  CONSTRAINT `tour_ibfk_2` FOREIGN KEY (`tour_category`) REFERENCES `tour_category` (`id`),
  CONSTRAINT `tour_ibfk_3` FOREIGN KEY (`season`) REFERENCES `seasons` (`id`),
  CONSTRAINT `tour_ibfk_4` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `tour_condition` (
  `tour_condition_id` int NOT NULL AUTO_INCREMENT,
  `tour_id` int NOT NULL,
  `condition_text` text NOT NULL,
  `display_order` int DEFAULT '0',
  `status_id` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`tour_condition_id`),
  KEY `fk_tour_condition_tour` (`tour_id`),
  KEY `fk_tour_condition_status` (`status_id`),
  KEY `fk_tour_condition_terminated_by` (`terminated_by`),
  CONSTRAINT `fk_tour_condition_status` FOREIGN KEY (`status_id`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_tour_condition_terminated_by` FOREIGN KEY (`terminated_by`) REFERENCES `user` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_tour_condition_tour` FOREIGN KEY (`tour_id`) REFERENCES `tour` (`tour_id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `tour_day_accommodation` (
  `tour_day_accommodation_id` int NOT NULL AUTO_INCREMENT,
  `tour_id` int NOT NULL,
  `day` int NOT NULL,
  `breakfast` tinyint(1) DEFAULT '0',
  `breakfast_description` text,
  `lunch` tinyint(1) DEFAULT '0',
  `lunch_description` text,
  `dinner` tinyint(1) DEFAULT '0',
  `dinner_description` text,
  `morning_tea` tinyint(1) DEFAULT '0',
  `morning_tea_description` text,
  `evening_tea` tinyint(1) DEFAULT '0',
  `evening_tea_description` text,
  `snacks` tinyint(1) DEFAULT '0',
  `snack_note` text,
  `hotel_id` int DEFAULT NULL,
  `transport_id` int DEFAULT NULL,
  `other_notes` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  PRIMARY KEY (`tour_day_accommodation_id`),
  UNIQUE KEY `uq_tour_day` (`tour_id`,`day`),
  KEY `fk_tour_day_accommodation_hotel` (`hotel_id`),
  KEY `fk_tour_day_accommodation_transport` (`transport_id`),
  CONSTRAINT `fk_tour_day_accommodation_hotel` FOREIGN KEY (`hotel_id`) REFERENCES `service_provider` (`service_provider_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_tour_day_accommodation_tour` FOREIGN KEY (`tour_id`) REFERENCES `tour` (`tour_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_tour_day_accommodation_transport` FOREIGN KEY (`transport_id`) REFERENCES `vehicles` (`vehicle_id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE `tour_destination` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tour_id` int NOT NULL,
  `destination_id` int NOT NULL,
  `activities_id` int DEFAULT NULL,
  `day` int DEFAULT NULL,
  `status` int NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `destination_id` (`destination_id`),
  KEY `tour_destination_ibfk_1` (`tour_id`),
  KEY `fk_tour_destination_created_by` (`created_by`),
  KEY `fk_tour_destination_updated_by` (`updated_by`),
  KEY `fk_tour_destination_terminated_by` (`terminated_by`),
  CONSTRAINT `fk_tour_destination_created_by` FOREIGN KEY (`created_by`) REFERENCES `user` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_tour_destination_terminated_by` FOREIGN KEY (`terminated_by`) REFERENCES `user` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_tour_destination_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `user` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE `tour_exclusion` (
  `tour_exclusion_id` int NOT NULL AUTO_INCREMENT,
  `tour_id` int NOT NULL,
  `exclusion_text` text NOT NULL,
  `display_order` int DEFAULT '0',
  `status_id` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`tour_exclusion_id`),
  KEY `fk_tour_exclusion_tour` (`tour_id`),
  KEY `fk_tour_exclusion_status` (`status_id`),
  KEY `fk_tour_exclusion_terminated_by` (`terminated_by`),
  CONSTRAINT `fk_tour_exclusion_status` FOREIGN KEY (`status_id`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_tour_exclusion_terminated_by` FOREIGN KEY (`terminated_by`) REFERENCES `user` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_tour_exclusion_tour` FOREIGN KEY (`tour_id`) REFERENCES `tour` (`tour_id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `tour_images` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tour_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `image_url` varchar(500) DEFAULT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tour_id` (`tour_id`),
  KEY `status` (`status`),
  CONSTRAINT `tour_images_ibfk_1` FOREIGN KEY (`tour_id`) REFERENCES `tour` (`tour_id`),
  CONSTRAINT `tour_images_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `tour_inclusion` (
  `tour_inclusion_id` int NOT NULL AUTO_INCREMENT,
  `tour_id` int NOT NULL,
  `inclusion_text` text NOT NULL,
  `display_order` int DEFAULT '0',
  `status_id` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`tour_inclusion_id`),
  KEY `fk_tour_inclusion_tour` (`tour_id`),
  KEY `fk_tour_inclusion_status` (`status_id`),
  KEY `fk_tour_inclusion_terminated_by` (`terminated_by`),
  CONSTRAINT `fk_tour_inclusion_status` FOREIGN KEY (`status_id`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_tour_inclusion_terminated_by` FOREIGN KEY (`terminated_by`) REFERENCES `user` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_tour_inclusion_tour` FOREIGN KEY (`tour_id`) REFERENCES `tour` (`tour_id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `tour_schedule` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `tour_id` int NOT NULL,
  `assume_start_date` date DEFAULT NULL,
  `assume_end_date` date DEFAULT NULL,
  `duration_start` int DEFAULT NULL,
  `duration_end` int DEFAULT NULL,
  `special_note` text,
  `description` text,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tour_id` (`tour_id`),
  KEY `status` (`status`),
  CONSTRAINT `tour_schedule_ibfk_1` FOREIGN KEY (`tour_id`) REFERENCES `tour` (`tour_id`),
  CONSTRAINT `tour_schedule_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `tour_travel_tips` (
  `tour_travel_tip_id` int NOT NULL AUTO_INCREMENT,
  `tour_id` int NOT NULL,
  `tip_title` varchar(150) DEFAULT NULL,
  `tip_description` text NOT NULL,
  `display_order` int DEFAULT '1',
  `status_id` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`tour_travel_tip_id`),
  KEY `tour_id` (`tour_id`),
  KEY `status_id` (`status_id`),
  CONSTRAINT `tour_travel_tips_ibfk_1` FOREIGN KEY (`tour_id`) REFERENCES `tour` (`tour_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `tour_travel_tips_ibfk_2` FOREIGN KEY (`status_id`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `tour_wishlist` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `tour_id` int NOT NULL,
  `status_id` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `tour_id` (`tour_id`),
  KEY `status_id` (`status_id`),
  CONSTRAINT `tour_wishlist_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `tour_wishlist_ibfk_2` FOREIGN KEY (`tour_id`) REFERENCES `tour` (`tour_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `tour_wishlist_ibfk_3` FOREIGN KEY (`status_id`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `tour_history` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tour_schedule_id` int NOT NULL,
  `package_id` int DEFAULT NULL,
  `number_of_participate` int DEFAULT NULL,
  `rating` decimal(3,2) DEFAULT NULL,
  `duration` int DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `status` int NOT NULL,
  `color` varchar(50) DEFAULT NULL,
  `hover_color` varchar(50) DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `vehicle_number` varchar(255) DEFAULT NULL,
  `driver_id` int DEFAULT NULL,
  `guide_id` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tour_schedule_id` (`tour_schedule_id`),
  KEY `package_id` (`package_id`),
  KEY `status` (`status`),
  CONSTRAINT `tour_history_ibfk_1` FOREIGN KEY (`tour_schedule_id`) REFERENCES `tour_schedule` (`id`),
  CONSTRAINT `tour_history_ibfk_2` FOREIGN KEY (`package_id`) REFERENCES `packages` (`package_id`),
  CONSTRAINT `tour_history_ibfk_3` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `tour_history_images` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tour_schedule_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `status` int NOT NULL,
  `image_url` varchar(500) DEFAULT NULL,
  `color` varchar(50) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tour_schedule_id` (`tour_schedule_id`),
  KEY `status` (`status`),
  CONSTRAINT `tour_history_images_ibfk_1` FOREIGN KEY (`tour_schedule_id`) REFERENCES `tour_schedule` (`id`),
  CONSTRAINT `tour_history_images_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `tour_review` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tour_schedule_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `review` text,
  `rating` decimal(3,2) DEFAULT NULL,
  `description` text,
  `status` int NOT NULL,
  `number_of_participate` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tour_schedule_id` (`tour_schedule_id`),
  KEY `status` (`status`),
  CONSTRAINT `tour_review_ibfk_1` FOREIGN KEY (`tour_schedule_id`) REFERENCES `tour_schedule` (`id`),
  CONSTRAINT `tour_review_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `tour_review_images` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tour_review_id` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `image_url` varchar(500) DEFAULT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tour_review_id` (`tour_review_id`),
  KEY `status` (`status`),
  CONSTRAINT `tour_review_images_ibfk_1` FOREIGN KEY (`tour_review_id`) REFERENCES `tour_review` (`id`),
  CONSTRAINT `tour_review_images_ibfk_2` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`)
);

CREATE TABLE `tour_review_comment` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tour_review_id` int NOT NULL,
  `parent_comment_id` int DEFAULT NULL,
  `user_id` int NOT NULL,
  `comment` text NOT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tour_review_id` (`tour_review_id`),
  KEY `parent_comment_id` (`parent_comment_id`),
  KEY `user_id` (`user_id`),
  KEY `status` (`status`),
  CONSTRAINT `tour_review_comment_ibfk_1` FOREIGN KEY (`tour_review_id`) REFERENCES `tour_review` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `tour_review_comment_ibfk_2` FOREIGN KEY (`parent_comment_id`) REFERENCES `tour_review_comment` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `tour_review_comment_ibfk_3` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `tour_review_comment_ibfk_4` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `tour_review_reaction` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tour_review_id` int NOT NULL,
  `user_id` int NOT NULL,
  `reaction_type_id` int NOT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tour_review_id` (`tour_review_id`,`user_id`,`reaction_type_id`),
  KEY `user_id` (`user_id`),
  KEY `reaction_type_id` (`reaction_type_id`),
  KEY `status` (`status`),
  CONSTRAINT `tour_review_reaction_ibfk_1` FOREIGN KEY (`tour_review_id`) REFERENCES `tour_review` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `tour_review_reaction_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `tour_review_reaction_ibfk_3` FOREIGN KEY (`reaction_type_id`) REFERENCES `reaction_type` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `tour_review_reaction_ibfk_4` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `tour_review_comment_reaction` (
  `id` int NOT NULL AUTO_INCREMENT,
  `comment_id` int NOT NULL,
  `user_id` int NOT NULL,
  `reaction_type_id` int NOT NULL,
  `status` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `comment_id` (`comment_id`,`user_id`,`reaction_type_id`),
  KEY `user_id` (`user_id`),
  KEY `reaction_type_id` (`reaction_type_id`),
  KEY `status` (`status`),
  CONSTRAINT `tour_review_comment_reaction_ibfk_1` FOREIGN KEY (`comment_id`) REFERENCES `tour_review_comment` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `tour_review_comment_reaction_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `tour_review_comment_reaction_ibfk_3` FOREIGN KEY (`reaction_type_id`) REFERENCES `reaction_type` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `tour_review_comment_reaction_ibfk_4` FOREIGN KEY (`status`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE `tour_wishlist_history` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `tour_id` int NOT NULL,
  `wishlist_id` int NOT NULL,
  `status_id` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `tour_id` (`tour_id`),
  KEY `wishlist_id` (`wishlist_id`),
  KEY `status_id` (`status_id`),
  CONSTRAINT `tour_wishlist_history_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `tour_wishlist_history_ibfk_2` FOREIGN KEY (`tour_id`) REFERENCES `tour` (`tour_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `tour_wishlist_history_ibfk_3` FOREIGN KEY (`wishlist_id`) REFERENCES `tour_wishlist` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `tour_wishlist_history_ibfk_4` FOREIGN KEY (`status_id`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);