INSERT INTO `travelagencydb`.`tour_category`
(`id`,
`name`,
`description`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{name: }>,
<{description: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`tour_type`
(`id`,
`name`,
`description`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{name: }>,
<{description: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`tour_hero_section`
(`id`,
`name`,
`image_url`,
`title`,
`subtitle`,
`description`,
`primary_button_text`,
`primary_button_link`,
`secondary_button_text`,
`secondary_button_link`,
`status`,
`order`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{name: }>,
<{image_url: }>,
<{title: }>,
<{subtitle: }>,
<{description: }>,
<{primary_button_text: }>,
<{primary_button_link: }>,
<{secondary_button_text: }>,
<{secondary_button_link: }>,
<{status: }>,
<{order: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`tour`
(`tour_id`,
`name`,
`description`,
`tour_type`,
`tour_category`,
`duration`,
`latitude`,
`longitude`,
`start_location`,
`end_location`,
`season`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`,
`assign_to`,
`assign_message`)
VALUES
(<{tour_id: }>,
<{name: }>,
<{description: }>,
<{tour_type: }>,
<{tour_category: }>,
<{duration: }>,
<{latitude: }>,
<{longitude: }>,
<{start_location: }>,
<{end_location: }>,
<{season: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>,
<{assign_to: }>,
<{assign_message: This tour is managed by a dedicated coordinator who will assist with planning, bookings, and support for a smooth travel experience.}>);

CREATE TABLE `tour_condition` (
  `tour_condition_id` int NOT NULL AUTO_INCREMENT,
  `tour_id` int NOT NULL,
  `condition_text` text NOT NULL,
  `display_order` int DEFAULT '0',
  `status_id` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` int DEFAULT NULL,
  `terminated_at` timestamp NULL DEFAULT NULL,
  `terminated_by` int DEFAULT NULL,
  PRIMARY KEY (`tour_condition_id`),
  KEY `fk_tour_condition_tour` (`tour_id`),
  KEY `fk_tour_condition_status` (`status_id`),
  KEY `fk_tour_condition_terminated_by` (`terminated_by`),
  CONSTRAINT `fk_tour_condition_status` FOREIGN KEY (`status_id`) REFERENCES `common_status` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_tour_condition_terminated_by` FOREIGN KEY (`terminated_by`) REFERENCES `user` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_tour_condition_tour` FOREIGN KEY (`tour_id`) REFERENCES `tour` (`tour_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
INSERT INTO `travelagencydb`.`tour_day_accommodation`
(`tour_day_accommodation_id`,
`tour_id`,
`day`,
`breakfast`,
`breakfast_description`,
`lunch`,
`lunch_description`,
`dinner`,
`dinner_description`,
`morning_tea`,
`morning_tea_description`,
`evening_tea`,
`evening_tea_description`,
`snacks`,
`snack_note`,
`hotel_id`,
`transport_id`,
`other_notes`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`)
VALUES
(<{tour_day_accommodation_id: }>,
<{tour_id: }>,
<{day: }>,
<{breakfast: 0}>,
<{breakfast_description: }>,
<{lunch: 0}>,
<{lunch_description: }>,
<{dinner: 0}>,
<{dinner_description: }>,
<{morning_tea: 0}>,
<{morning_tea_description: }>,
<{evening_tea: 0}>,
<{evening_tea_description: }>,
<{snacks: 0}>,
<{snack_note: }>,
<{hotel_id: }>,
<{transport_id: }>,
<{other_notes: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>);

INSERT INTO `travelagencydb`.`tour_destination`
(`id`,
`tour_id`,
`destination_id`,
`activities_id`,
`day`,
`status`,
`created_at`,
`updated_at`,
`terminated_at`,
`created_by`,
`updated_by`,
`terminated_by`)
VALUES
(<{id: }>,
<{tour_id: }>,
<{destination_id: }>,
<{activities_id: }>,
<{day: }>,
<{status: 1}>,
<{created_at: CURRENT_TIMESTAMP}>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{terminated_at: }>,
<{created_by: }>,
<{updated_by: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`tour_exclusion`
(`tour_exclusion_id`,
`tour_id`,
`exclusion_text`,
`display_order`,
`status_id`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{tour_exclusion_id: }>,
<{tour_id: }>,
<{exclusion_text: }>,
<{display_order: 0}>,
<{status_id: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`tour_images`
(`id`,
`tour_id`,
`name`,
`description`,
`image_url`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{tour_id: }>,
<{name: }>,
<{description: }>,
<{image_url: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);


INSERT INTO `travelagencydb`.`tour_inclusion`
(`tour_inclusion_id`,
`tour_id`,
`inclusion_text`,
`display_order`,
`status_id`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{tour_inclusion_id: }>,
<{tour_id: }>,
<{inclusion_text: }>,
<{display_order: 0}>,
<{status_id: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`tour_schedule`
(`id`,
`name`,
`tour_id`,
`assume_start_date`,
`assume_end_date`,
`duration_start`,
`duration_end`,
`special_note`,
`description`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{name: }>,
<{tour_id: }>,
<{assume_start_date: }>,
<{assume_end_date: }>,
<{duration_start: }>,
<{duration_end: }>,
<{special_note: }>,
<{description: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`tour_travel_tips`
(`tour_travel_tip_id`,
`tour_id`,
`tip_title`,
`tip_description`,
`display_order`,
`status_id`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{tour_travel_tip_id: }>,
<{tour_id: }>,
<{tip_title: }>,
<{tip_description: }>,
<{display_order: 1}>,
<{status_id: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`tour_wishlist`
(`id`,
`user_id`,
`tour_id`,
`status_id`,
`created_at`)
VALUES
(<{id: }>,
<{user_id: }>,
<{tour_id: }>,
<{status_id: }>,
<{created_at: CURRENT_TIMESTAMP}>);

INSERT INTO `travelagencydb`.`tour_history`
(`id`,
`tour_schedule_id`,
`package_id`,
`number_of_participate`,
`rating`,
`duration`,
`name`,
`description`,
`status`,
`color`,
`hover_color`,
`start_date`,
`end_date`,
`vehicle_number`,
`driver_id`,
`guide_id`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{tour_schedule_id: }>,
<{package_id: }>,
<{number_of_participate: }>,
<{rating: }>,
<{duration: }>,
<{name: }>,
<{description: }>,
<{status: }>,
<{color: }>,
<{hover_color: }>,
<{start_date: }>,
<{end_date: }>,
<{vehicle_number: }>,
<{driver_id: }>,
<{guide_id: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`tour_history_images`
(`id`,
`tour_schedule_id`,
`name`,
`description`,
`status`,
`image_url`,
`color`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{tour_schedule_id: }>,
<{name: }>,
<{description: }>,
<{status: }>,
<{image_url: }>,
<{color: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`tour_review`
(`id`,
`tour_schedule_id`,
`name`,
`review`,
`rating`,
`description`,
`status`,
`number_of_participate`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{tour_schedule_id: }>,
<{name: }>,
<{review: }>,
<{rating: }>,
<{description: }>,
<{status: }>,
<{number_of_participate: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`tour_review_images`
(`id`,
`tour_review_id`,
`name`,
`description`,
`image_url`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{tour_review_id: }>,
<{name: }>,
<{description: }>,
<{image_url: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`tour_review_comment`
(`id`,
`tour_review_id`,
`parent_comment_id`,
`user_id`,
`comment`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{tour_review_id: }>,
<{parent_comment_id: }>,
<{user_id: }>,
<{comment: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`tour_review_reaction`
(`id`,
`tour_review_id`,
`user_id`,
`reaction_type_id`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`)
VALUES
(<{id: }>,
<{tour_review_id: }>,
<{user_id: }>,
<{reaction_type_id: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>);

INSERT INTO `travelagencydb`.`tour_review_comment_reaction`
(`id`,
`comment_id`,
`user_id`,
`reaction_type_id`,
`status`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`)
VALUES
(<{id: }>,
<{comment_id: }>,
<{user_id: }>,
<{reaction_type_id: }>,
<{status: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>);

INSERT INTO `travelagencydb`.`tour_wishlist_history`
(`id`,
`user_id`,
`tour_id`,
`wishlist_id`,
`status_id`,
`created_at`)
VALUES
(<{id: }>,
<{user_id: }>,
<{tour_id: }>,
<{wishlist_id: }>,
<{status_id: }>,
<{created_at: CURRENT_TIMESTAMP}>);