INSERT INTO `travelagencydb`.`why_choose_us_status`
(`id`,
`name`,
`description`,
`common_status_id`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{name: }>,
<{description: }>,
<{common_status_id: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`why_choose_us`
(`id`,
`name`,
`title`,
`sub_title`,
`description`,
`image_url`,
`icon_url`,
`clicked_url`,
`color`,
`why_choose_us_status_id`,
`order`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{name: }>,
<{title: }>,
<{sub_title: }>,
<{description: }>,
<{image_url: }>,
<{icon_url: }>,
<{clicked_url: }>,
<{color: }>,
<{why_choose_us_status_id: }>,
<{order: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);
