INSERT INTO `travelagencydb`.`hero_section_status`
(`id`,
`name`,
`description`,
`common_status_id`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{name: }>,
<{description: }>,
<{common_status_id: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`hero_section`
(`id`,
`name`,
`image_url`,
`title`,
`subtitle`,
`description`,
`primary_button_text`,
`primary_button_link`,
`secondary_button_text`,
`secondary_button_link`,
`hero_section_status_id`,
`order`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{name: }>,
<{image_url: }>,
<{title: }>,
<{subtitle: }>,
<{description: }>,
<{primary_button_text: }>,
<{primary_button_link: }>,
<{secondary_button_text: }>,
<{secondary_button_link: }>,
<{hero_section_status_id: }>,
<{order: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);


INSERT INTO `travelagencydb`.`about_us_hero_section`
(`id`,
`name`,
`image_url`,
`title`,
`subtitle`,
`description`,
`primary_button_text`,
`primary_button_link`,
`secondary_button_text`,
`secondary_button_link`,
`status`,
`order`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{name: }>,
<{image_url: }>,
<{title: }>,
<{subtitle: }>,
<{description: }>,
<{primary_button_text: }>,
<{primary_button_link: }>,
<{secondary_button_text: }>,
<{secondary_button_link: }>,
<{status: }>,
<{order: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`contact_us_hero_section`
(`id`,
`name`,
`image_url`,
`title`,
`subtitle`,
`description`,
`primary_button_text`,
`primary_button_link`,
`secondary_button_text`,
`secondary_button_link`,
`status`,
`order`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{name: }>,
<{image_url: }>,
<{title: }>,
<{subtitle: }>,
<{description: }>,
<{primary_button_text: }>,
<{primary_button_link: }>,
<{secondary_button_text: }>,
<{secondary_button_link: }>,
<{status: }>,
<{order: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`blog_hero_section`
(`id`,
`name`,
`image_url`,
`title`,
`subtitle`,
`description`,
`primary_button_text`,
`primary_button_link`,
`secondary_button_text`,
`secondary_button_link`,
`status`,
`order`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{name: }>,
<{image_url: }>,
<{title: }>,
<{subtitle: }>,
<{description: }>,
<{primary_button_text: }>,
<{primary_button_link: }>,
<{secondary_button_text: }>,
<{secondary_button_link: }>,
<{status: }>,
<{order: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`faq_hero_section`
(`id`,
`name`,
`image_url`,
`title`,
`subtitle`,
`description`,
`primary_button_text`,
`primary_button_link`,
`secondary_button_text`,
`secondary_button_link`,
`status`,
`order`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{name: }>,
<{image_url: }>,
<{title: }>,
<{subtitle: }>,
<{description: }>,
<{primary_button_text: }>,
<{primary_button_link: }>,
<{secondary_button_text: }>,
<{secondary_button_link: }>,
<{status: }>,
<{order: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`tour_hero_section`
(`id`,
`name`,
`image_url`,
`title`,
`subtitle`,
`description`,
`primary_button_text`,
`primary_button_link`,
`secondary_button_text`,
`secondary_button_link`,
`status`,
`order`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{name: }>,
<{image_url: }>,
<{title: }>,
<{subtitle: }>,
<{description: }>,
<{primary_button_text: }>,
<{primary_button_link: }>,
<{secondary_button_text: }>,
<{secondary_button_link: }>,
<{status: }>,
<{order: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);


INSERT INTO `travelagencydb`.`package_hero_section`
(`id`,
`name`,
`image_url`,
`title`,
`subtitle`,
`description`,
`primary_button_text`,
`primary_button_link`,
`secondary_button_text`,
`secondary_button_link`,
`status`,
`order`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{name: }>,
<{image_url: }>,
<{title: }>,
<{subtitle: }>,
<{description: }>,
<{primary_button_text: }>,
<{primary_button_link: }>,
<{secondary_button_text: }>,
<{secondary_button_link: }>,
<{status: }>,
<{order: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

INSERT INTO `travelagencydb`.`destination_hero_section`
(`id`,
`name`,
`image_url`,
`title`,
`subtitle`,
`description`,
`primary_button_text`,
`primary_button_link`,
`secondary_button_text`,
`secondary_button_link`,
`status`,
`order`,
`created_at`,
`created_by`,
`updated_at`,
`updated_by`,
`terminated_at`,
`terminated_by`)
VALUES
(<{id: }>,
<{name: }>,
<{image_url: }>,
<{title: }>,
<{subtitle: }>,
<{description: }>,
<{primary_button_text: }>,
<{primary_button_link: }>,
<{secondary_button_text: }>,
<{secondary_button_link: }>,
<{status: }>,
<{order: }>,
<{created_at: CURRENT_TIMESTAMP}>,
<{created_by: }>,
<{updated_at: CURRENT_TIMESTAMP}>,
<{updated_by: }>,
<{terminated_at: }>,
<{terminated_by: }>);

